=== cu-clear/verbnet/verbnet3.4/vn_class-3.dtd
<!ELEMENT VNCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNCLASS ID ID #REQUIRED
                  xmlns:xsi CDATA #IMPLIED
                  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT VNSUBCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNSUBCLASS ID ID #REQUIRED>

<!ELEMENT MEMBERS (MEMBER*)>
<!ELEMENT THEMROLES (THEMROLE*)>
<!ELEMENT SELRESTRS (SELRESTR|SELRESTRS)*>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT FRAMES (FRAME*)>
<!ELEMENT SUBCLASSES (VNSUBCLASS*)>

<!ELEMENT FRAME (DESCRIPTION,EXAMPLES,SYNTAX,SEMANTICS)>
<!ELEMENT EXAMPLES (EXAMPLE*)>

<!ELEMENT MEMBER EMPTY>
 <!ATTLIST MEMBER name CDATA #REQUIRED
                  wn CDATA #REQUIRED
                  grouping CDATA #IMPLIED
                  fn_mapping CDATA #REQUIRED
                  verbnet_key CDATA #REQUIRED
                  features CDATA #REQUIRED>

<!ELEMENT THEMROLE (SELRESTRS)>
<!ATTLIST THEMROLE type CDATA #REQUIRED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT DESCRIPTION EMPTY>
<!ATTLIST DESCRIPTION primary CDATA #REQUIRED
                      secondary CDATA #IMPLIED
                      descriptionNumber CDATA #REQUIRED 
                      xtag CDATA #REQUIRED> 

<!ELEMENT EXAMPLE (#PCDATA)>
<!ELEMENT SYNTAX (NP|VERB|ADJ|ADV|PREP|LEX)+>
<!ELEMENT SEMANTICS (PRED+)>
<!ELEMENT GL (QUALIA,EVENT_STRUCTURE,SUBCATEGORISATION)>

<!ELEMENT NP (SELRESTRS|SELRESTRS)>
<!ATTLIST NP value CDATA #REQUIRED>

<!ELEMENT SELRESTRS (SELRESTR*)>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT VERB EMPTY>
<!ELEMENT ADJ EMPTY>
<!ELEMENT ADV EMPTY>

<!ELEMENT PREP (SELRESTRS)>
<!ATTLIST PREP value CDATA #IMPLIED>

<!ELEMENT LEX EMPTY>
<!ATTLIST LEX value CDATA #REQUIRED>

<!ELEMENT PRED (ARGS)>
<!ATTLIST PRED bool CDATA #IMPLIED
               value CDATA #REQUIRED>

<!ELEMENT ARGS (ARG+)>
<!ELEMENT ARG EMPTY>
<!ATTLIST ARG type (Event|ThemRole|VerbSpecific|Constant|PredSpecific) #REQUIRED
              value CDATA #REQUIRED>

<!ELEMENT QUALIA (#PCDATA)>
<!ELEMENT EVENT_STRUCTURE (#PCDATA)>
<!ELEMENT SUBCATEGORISATION (#PCDATA)>

=== cu-clear/verbnet/verbnet3.4/acquiesce-95.1.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="acquiesce-95.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="defer.02" name="defer" verbnet_key="defer#1" wn="defer%2:32:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Pivot">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V" secondary="Basic Intransitive" xtag="0.1"/>
   <EXAMPLES>
    <EXAMPLE>
     The enemy soldiers yielded.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="yield">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="?Pivot"/>
      <ARG type="ThemRole" value="?Theme"/>
     </ARGS>
    </PRED>
    <PRED value="authority_relationship">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="?Pivot"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V PP.pivot" secondary="NP-PP; to-PP" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     The enemy soldiers yielded to us.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <PREP value="to">
     <SELRESTRS/>
    </PREP>
    <NP value="Pivot">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="yield">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Pivot"/>
      <ARG type="ThemRole" value="?Theme"/>
     </ARGS>
    </PRED>
    <PRED value="authority_relationship">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Pivot"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 <SUBCLASSES>
  <VNSUBCLASS ID="acquiesce-95.1-1">
   <MEMBERS>
    <MEMBER fn_mapping="None" grouping="accede.01" name="accede" verbnet_key="accede#1" wn="accede%2:32:00 accede%2:32:01" features=""/>
    <MEMBER fn_mapping="None" grouping="bow.03" name="bow" verbnet_key="bow#1" wn="bow%2:32:01" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="capitulate" verbnet_key="capitulate#1" wn="capitulate%2:33:00" features=""/>  
    <MEMBER fn_mapping="Conquering" grouping="fall.04" name="fall" verbnet_key="fall#1" wn="fall%2:40:05" features=""/>
    <MEMBER fn_mapping="None" grouping="give.05" name="give_way" verbnet_key="give_way#1" wn="give_way%2:38:01 give_way%2:30:01" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="give_in" verbnet_key="give_in#1" wn="give_in%2:32:02 give_in%2:32:01" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="succumb" verbnet_key="succumb#1" wn="succumb%2:32:00" features=""/>
    <MEMBER fn_mapping="None" grouping="yield.02" name="yield" verbnet_key="yield#1" wn="yield%2:30:00 yield%2:40:01 yield%2:33:00 yield%2:32:00" features=""/>
   </MEMBERS>
   <THEMROLES/>
   <FRAMES>
    <FRAME>
     <DESCRIPTION descriptionNumber="8.1" primary="NP V PP.theme" secondary="NP-PP; to-PP" xtag="0.2"/>
     <EXAMPLES>
      <EXAMPLE>
       The enemy soldiers submitted to demands.
      </EXAMPLE>
     </EXAMPLES>
     <SYNTAX>
      <NP value="Agent">
       <SELRESTRS/>
      </NP>
      <VERB/>
      <PREP value="to">
       <SELRESTRS/>
      </PREP>
      <NP value="Theme">
       <SELRESTRS/>
      </NP>
     </SYNTAX>
     <SEMANTICS>
      <PRED value="yield">
       <ARGS>
        <ARG type="Event" value="e1"/>
        <ARG type="ThemRole" value="Agent"/>
        <ARG type="ThemRole" value="?Pivot"/>
        <ARG type="ThemRole" value="Theme"/>
       </ARGS>
      </PRED>
      <PRED value="authority_relationship">
       <ARGS>
        <ARG type="Event" value="e2"/>
        <ARG type="ThemRole" value="?Pivot"/>
        <ARG type="ThemRole" value="Agent"/>
       </ARGS>
      </PRED>
     </SEMANTICS>
    </FRAME>
   </FRAMES>
   <SUBCLASSES>
    <VNSUBCLASS ID="acquiesce-95.1-1-1">
     <MEMBERS>
      <MEMBER fn_mapping="None" grouping="" name="acquiesce" verbnet_key="acquiesce#1" wn="acquiesce%2:32:00" features=""/>
      <MEMBER fn_mapping="None" grouping="consent.01" name="consent" verbnet_key="consent#1" wn="consent%2:32:00" features=""/>
      <MEMBER fn_mapping="None" grouping="submit.01" name="submit" verbnet_key="submit#1" wn="submit%2:33:00" features=""/>
     </MEMBERS>
     <THEMROLES/>
     <FRAMES>
      <FRAME>
       <DESCRIPTION descriptionNumber="8.1" primary="NP V S_INF" secondary="TO_INF; N-SC" xtag="0.2"/>
       <EXAMPLES>
        <EXAMPLE>
         The king acquiesced to be in the same room with the paupers
        </EXAMPLE>
       </EXAMPLES>
       <SYNTAX>
        <NP value="Agent">
         <SELRESTRS/>
        </NP>
        <VERB/>
        <NP value="Theme">
         <SELRESTRS>
          <SELRESTR Value="+" type="sc_to_inf"/>
         </SELRESTRS>
        </NP>
       </SYNTAX>
       <SEMANTICS>
        <PRED value="yield">
         <ARGS>
          <ARG type="Event" value="e1"/>
          <ARG type="ThemRole" value="Agent"/>
          <ARG type="ThemRole" value="?Pivot"/>
          <ARG type="ThemRole" value="Theme"/>
         </ARGS>
        </PRED>
        <PRED value="authority_relationship">
          <ARGS>
          <ARG type="Event" value="e2"/>
          <ARG type="ThemRole" value="?Pivot"/>
          <ARG type="ThemRole" value="Agent"/>
         </ARGS>
        </PRED>
       </SEMANTICS>
      </FRAME>
     </FRAMES>
     <SUBCLASSES/>
    </VNSUBCLASS>
   </SUBCLASSES>
  </VNSUBCLASS>
 </SUBCLASSES>
</FRAMES>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/absorb-39.8.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="absorb-39.8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="absorb.01" name="absorb" verbnet_key="absorb#1" wn="absorb%2:35:00 absorb%2:43:00" features=""/>
  <MEMBER fn_mapping="None" grouping="ingest.01" name="ingest" verbnet_key="ingest#1" wn="ingest%2:34:00" features=""/>
  <MEMBER fn_mapping="Ingest_substance" grouping="take.11" name="take" verbnet_key="take#1" wn="take_in%2:34:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Goal">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Source">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     The cotton absorbed the water.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Goal">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="?Source"/>
     </ARGS>
    </PRED>
    <PRED value="motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="contain">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Goal"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="2.1" primary="NP V NP PP.source" secondary="NP-PP; Source-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     The cow took in nutrients from her feed.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Goal">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <PREP value="from">
     <SELRESTRS/>
    </PREP>
    <NP value="Source">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Source"/>
     </ARGS>
    </PRED>
    <PRED value="motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="contain">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Goal"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/coil-9.6.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="coil-9.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="loop.02" name="loop" verbnet_key="loop#1" wn="loop%2:36:00 loop%2:35:00" features=""/>
  <MEMBER fn_mapping="Reshaping" grouping="roll.02" name="roll" verbnet_key="roll#3" wn="roll%2:35:00" features=""/>
  <MEMBER fn_mapping="Moving_in_place" grouping="rotate.01" name="rotate" verbnet_key="rotate#1" wn="rotate%2:38:01" features=""/>
  <MEMBER fn_mapping="Perception_body" grouping="spin.01" name="spin" verbnet_key="spin#2" wn="spin%2:38:02" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="swirl" verbnet_key="swirl#1" wn="swirl%2:38:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="twine" verbnet_key="twine#1" wn="twine%2:35:03" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="whirl" verbnet_key="whirl#1" wn="whirl%2:38:02" features=""/>
  <MEMBER fn_mapping="Motion" grouping="wind.02" name="wind" verbnet_key="wind#1" wn="wind%2:35:06" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS>
    <SELRESTR Value="+" type="int_control"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS>
    <SELRESTR Value="+" type="nonrigid"/>
    <SELRESTR Value="+" type="elongated"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Initial_Location">
   <SELRESTRS>
    <SELRESTR Value="+" type="location"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Destination">
   <SELRESTRS>
    <SELRESTR Value="+" type="location"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Axis">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.location" secondary="NP-PP; path-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Cora coiled the rope around the post.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="path"/>
     </SELRESTRS>
    </PREP>
    <NP value="Destination">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED bool="!" value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="?Initial_Location"/>
     </ARGS>
    </PRED>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="motion">
     <ARGS>
      <ARG type="Event" value="ë3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
    <PRED value="elliptical_motion">
     <ARGS>
      <ARG type="Event" value="ë3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e4"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e4"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="Event" value="ë3"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V PP.location" secondary="PP; path-PP" xtag=""/>
   <!--strongly prefers prep "around"-->
   <EXAMPLES>
    <EXAMPLE>
     The rope coiled around the post.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="path"/>
     </SELRESTRS>
    </PREP>
    <NP value="Destination">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED bool="!" value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="?Initial_Location"/>
     </ARGS>
    </PRED>
    <PRED value="motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
    <PRED value="elliptical_motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="1.1.1" primary="NP V ADV-Middle PP.location" secondary="Middle Construction" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     That type of rope coiled easily around the post.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <ADV/>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="path"/>
     </SELRESTRS>
    </PREP>
    <NP value="Destination">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED bool="!" value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="?Initial_Location"/>
     </ARGS>
    </PRED>
    <PRED value="motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
    <PRED value="elliptical_motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="has_physical_form">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="VerbSpecific" value="V_Form"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="ThemRole" value="Destination"/>
      <ARG type="PredSpecific" value="Trajectory"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES>
  <VNSUBCLASS ID="coil-9.6-1">
   <MEMBERS>
    <MEMBER fn_mapping="Hair_configuration" grouping="curl.01" name="curl" verbnet_key="curl#2" wn="curl%2:38:00 curl%2:35:01 curl%2:35:00" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="coil" verbnet_key="coil#1" wn="coil%2:35:00" features=""/>
    <MEMBER fn_mapping="Attaching" grouping="hook.01" name="hook" verbnet_key="hook#1" wn="" features=""/>
    <MEMBER fn_mapping="Cause_to_move_in_place" grouping="swing.01" name="swing" verbnet_key="swing#2" wn="swing%2:38:02 swing%2:38:03" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="twirl" verbnet_key="twirl#1" wn="twirl%2:38:01" features=""/>
    <MEMBER fn_mapping="None" grouping="twist.02" name="twist" verbnet_key="twist#1" wn="twist%2:30:00" features=""/>
   </MEMBERS>
   <THEMROLES/>
   <FRAMES>
    <FRAME>
     <DESCRIPTION descriptionNumber="" primary="NP V ADV-Middle" secondary="Middle Construction" xtag=""/>
     <EXAMPLES>
      <EXAMPLE>
       The rope curled upward.
      </EXAMPLE>
     </EXAMPLES>
     <SYNTAX>
      <NP value="Theme">
       <SELRESTRS/>
      </NP>
      <VERB/>
      <ADV value="Trajectory">
       <SELRESTRS/>
      </ADV>
     </SYNTAX>
     <SEMANTICS>
      <PRED value="has_physical_form">
       <ARGS>
        <ARG type="Event" value="E"/>
        <ARG type="ThemRole" value="Theme"/>
        <ARG type="VerbSpecific" value="V_Form"/>
       </ARGS>
      </PRED>
      <PRED value="fictive_motion">
       <ARGS>
        <ARG type="Event" value="E" />
        <ARG type="ThemRole" value="Theme" />
        <ARG type="PredSpecific" value="Trajectory" />
       </ARGS>
      </PRED>
     </SEMANTICS>
    </FRAME>
   </FRAMES>
   <SUBCLASSES/>
  </VNSUBCLASS>
 </SUBCLASSES>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/entity_specific_modes_being-47.2.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="entity_specific_modes_being-47.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <!--Each member adds a predicate for what the Theme is doing while it exists-->
  <MEMBER fn_mapping="None" grouping="" name="billow" verbnet_key="billow#1" wn="billow%2:38:02" features="end_state: specific_shape"/>
  <MEMBER fn_mapping="None" grouping="" name="bloom" verbnet_key="bloom#2" wn="bloom%2:30:00" features="entity_type: plant"/>
  <MEMBER fn_mapping="None" grouping="" name="blossom" verbnet_key="blossom#2" wn="blossom%2:30:01" features="entity_type: plant"/>
  <MEMBER fn_mapping="None" grouping="bristle.01" name="bristle" verbnet_key="bristle#2" wn="bristle%2:38:00" features=""/>
  <MEMBER fn_mapping="None" grouping="bulge.01" name="bulge" verbnet_key="bulge#2" wn="bulge%2:42:00" features="end_state: specific_shape"/>
  <MEMBER fn_mapping="None" grouping="burn.02" name="burn" verbnet_key="burn#2" wn="burn%2:43:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="effervesce" verbnet_key="effervesce#1" wn="effervesce%2:30:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="fester" verbnet_key="fester#2" wn="fester%2:29:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="fizz" verbnet_key="fizz#1" wn="fizz%2:30:00" features="end_state: specific_end_product"/>
  <MEMBER fn_mapping="Fluidic_motion" grouping="flow.01 flow.03" name="flow" verbnet_key="flow#2" wn="flow%2:38:00 flow%2:35:04" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="flower" verbnet_key="flower#2" wn="flower%2:30:00" features="entity_type: plant"/>
  <MEMBER fn_mapping="None" grouping="flux.01" name="flux" verbnet_key="flux#1" wn="flux%2:38:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="foam" verbnet_key="foam#1" wn="foam%2:30:05" features="entity_type: liquid"/>
  <MEMBER fn_mapping="None" grouping="froth.01" name="froth" verbnet_key="froth#1" wn="froth%2:30:00 froth%2:30:01" features="end_state: specific_end_product"/>
  <MEMBER fn_mapping="None" grouping="moil.02" name="moil" verbnet_key="moil#1" wn="moil%2:38:00" features=""/>
  <MEMBER fn_mapping="Giving_birth" grouping="propagate.01 propagate.02" name="propagate" verbnet_key="propagate#1" wn="propagate%2:38:01 propagate%2:29:00" features=""/>
  <MEMBER fn_mapping="None" grouping="rage.01" name="rage" verbnet_key="rage#1" wn="rage%2:42:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="ripple" verbnet_key="ripple#1" wn="ripple%2:39:00" features="end_state: specific_shape"/>
  <MEMBER fn_mapping="None" grouping="" name="roil" verbnet_key="roil#2" wn="roil%2:38:00" features=""/>
  <MEMBER fn_mapping="None" grouping="seethe.02" name="seethe" verbnet_key="seethe#2" wn="seethe%2:30:03 seethe%2:30:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="smolder" verbnet_key="smolder#1" wn="smolder%2:30:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="sprout" verbnet_key="sprout#2" wn="sprout%2:30:00 sprout%2:29:01" features="property_changed: existence; result: +create; entity_type: plant"/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Location">
   <SELRESTRS>
    <SELRESTR Value="+" type="location"/>
    <SELRESTR Value="-" type="region"/>
   </SELRESTRS>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V" secondary="Basic Intransitive" xtag="0.1"/>
   <EXAMPLES>
    <EXAMPLE>
     The beer foamed.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="VerbSpecific" value="V_Manner"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V PP.location" secondary="PP; locative-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     A fire raged in the mountains.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="loc"/>
     </SELRESTRS>
    </PREP>
    <NP value="Location">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="VerbSpecific" value="V_Manner"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Location"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="6.1" primary="There V NP" secondary="NP; Expletive-there Subject" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     There raged a fire.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <LEX value="there"/>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS>
      <SELRESTR Value="-" type="definite"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="VerbSpecific" value="V_Manner"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="6.2" primary="NP.location V NP" secondary="Locative Inversion" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     All through the mountains raged a fire.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="loc"/>
     </SELRESTRS>
    </PREP>
    <NP value="Location">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="VerbSpecific" value="V_Manner"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Location"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="2.3" primary="NP.location V PP.theme" secondary="PP; Location Subject, with-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     The garden flowered with roses.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Location">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <PREP value="with">
     <SELRESTRS/>
    </PREP>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="VerbSpecific" value="V_Manner"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Location"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>
