=== cu-clear/verbnet/verbnet3.4/vn_class-3.dtd
<!ELEMENT VNCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNCLASS ID ID #REQUIRED
                  xmlns:xsi CDATA #IMPLIED
                  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT VNSUBCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNSUBCLASS ID ID #REQUIRED>

<!ELEMENT MEMBERS (MEMBER*)>
<!ELEMENT THEMROLES (THEMROLE*)>
<!ELEMENT SELRESTRS (SELRESTR|SELRESTRS)*>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT FRAMES (FRAME*)>
<!ELEMENT SUBCLASSES (VNSUBCLASS*)>

<!ELEMENT FRAME (DESCRIPTION,EXAMPLES,SYNTAX,SEMANTICS)>
<!ELEMENT EXAMPLES (EXAMPLE*)>

<!ELEMENT MEMBER EMPTY>
 <!ATTLIST MEMBER name CDATA #REQUIRED
                  wn CDATA #REQUIRED
                  grouping CDATA #IMPLIED
                  fn_mapping CDATA #REQUIRED
                  verbnet_key CDATA #REQUIRED
                  features CDATA #REQUIRED>

<!ELEMENT THEMROLE (SELRESTRS)>
<!ATTLIST THEMROLE type CDATA #REQUIRED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT DESCRIPTION EMPTY>
<!ATTLIST DESCRIPTION primary CDATA #REQUIRED
                      secondary CDATA #IMPLIED
                      descriptionNumber CDATA #REQUIRED 
                      xtag CDATA #REQUIRED> 

<!ELEMENT EXAMPLE (#PCDATA)>
<!ELEMENT SYNTAX (NP|VERB|ADJ|ADV|PREP|LEX)+>
<!ELEMENT SEMANTICS (PRED+)>
<!ELEMENT GL (QUALIA,EVENT_STRUCTURE,SUBCATEGORISATION)>

<!ELEMENT NP (SELRESTRS|SELRESTRS)>
<!ATTLIST NP value CDATA #REQUIRED>

<!ELEMENT SELRESTRS (SELRESTR*)>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT VERB EMPTY>
<!ELEMENT ADJ EMPTY>
<!ELEMENT ADV EMPTY>

<!ELEMENT PREP (SELRESTRS)>
<!ATTLIST PREP value CDATA #IMPLIED>

<!ELEMENT LEX EMPTY>
<!ATTLIST LEX value CDATA #REQUIRED>

<!ELEMENT PRED (ARGS)>
<!ATTLIST PRED bool CDATA #IMPLIED
               value CDATA #REQUIRED>

<!ELEMENT ARGS (ARG+)>
<!ELEMENT ARG EMPTY>
<!ATTLIST ARG type (Event|ThemRole|VerbSpecific|Constant|PredSpecific) #REQUIRED
              value CDATA #REQUIRED>

<!ELEMENT QUALIA (#PCDATA)>
<!ELEMENT EVENT_STRUCTURE (#PCDATA)>
<!ELEMENT SUBCATEGORISATION (#PCDATA)>

=== cu-clear/verbnet/verbnet3.4/stalk-35.3.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="stalk-35.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="scent.02" name="scent" verbnet_key="scent#3" wn="scent%2:39:01" features=""/>
  <MEMBER fn_mapping="Perception_experience" grouping="smell.01" name="smell" verbnet_key="smell#4" wn="smell%2:39:01" features=""/>
  <MEMBER fn_mapping="Cotheme" grouping="stalk.01" name="stalk" verbnet_key="stalk#2" wn="stalk%2:38:03" features=""/>
  <MEMBER fn_mapping="None" grouping="taste.02" name="taste" verbnet_key="taste#4" wn="taste%2:34:00" features=""/>
  <MEMBER fn_mapping="None" grouping="track.02" name="track" verbnet_key="track#2" wn="track%2:38:00" features=""/>
  <MEMBER fn_mapping="None" grouping="whiff.01" name="whiff" verbnet_key="whiff#2" wn="whiff%2:39:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS>
    <SELRESTR Value="+" type="animate"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Location">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.theme" secondary="NP-PP; Theme-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I stalked the woods for game.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Location">
     <SELRESTRS/>
    </NP>
    <PREP value="for">
     <SELRESTRS/>
    </PREP>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="search">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Location"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.location" secondary="NP-PP; Location-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I stalked game in the woods.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="loc"/>
     </SELRESTRS>
    </PREP>
    <NP value="Location">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="search">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Location"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="" primary="NP V NP" secondary="Transitive" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I tracked prints.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="search">
     <ARGS>
      <ARG type="Event" value="ë"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="?Location"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/promote-102.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="promote-102" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="promote.01" name="promote" verbnet_key="promote#1" wn="promote%2:41:01 promote%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="advance.03 advance.04" name="advance" verbnet_key="advance#4" wn="advance%2:41:01 advance%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="boost.01" name="boost" verbnet_key="boost#1" wn="boost%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="further.01" name="further" verbnet_key="further#1" wn="further%2:41:00 further%2:41:01" features=""/>
  <MEMBER fn_mapping="Subjective_influence" grouping="encourage.01" name="encourage" verbnet_key="encourage#4" wn="encourage%2:41:00" features=""/>
  <MEMBER fn_mapping="Request" grouping="invite.01" name="invite" verbnet_key="invite#1" wn="invite%2:32:01" features=""/>
  <MEMBER fn_mapping="Convey_importance" grouping="emphasize.01" name="emphasize" verbnet_key="emphasize#1" wn="emphasize%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="underscore.01" name="underscore" verbnet_key="underscore#1" wn="underscore%2:32:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="NP" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     We promoted the cause.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="encourage">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V S_ING" secondary="ING-AC" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     We promoted writing novels.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS>
      <SELRESTR Value="+" type="ac_ing"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="encourage">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V S_ING" secondary="POSSING" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     We promoted their writing novels.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Theme">
     <SELRESTRS>
      <SELRESTR Value="+" type="poss_ing"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="encourage">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/terminus-47.9.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="terminus-47.9" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="begin.01" name="begin" verbnet_key="begin#2" wn="begin%2:42:00" features="+begin"/>
  <MEMBER fn_mapping="None" grouping="end.01" name="end" verbnet_key="end#2" wn="end%2:42:00" features="+end"/>
  <MEMBER fn_mapping="None" grouping="lead.03" name="lead" verbnet_key="lead#6" wn="lead%2:42:00 lead%2:42:03" features=""/>
  <MEMBER fn_mapping="None" grouping="start.01" name="start" verbnet_key="start#3" wn="start%2:42:00" features="+begin"/>
  <MEMBER fn_mapping="None" grouping="stop.04" name="stop" verbnet_key="stop#4" wn="stop%2:42:13" features="+end"/>
  <MEMBER fn_mapping="None" grouping="terminate.01" name="terminate" verbnet_key="terminate#3" wn="terminate%2:42:00" features="+end"/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Theme">
   <SELRESTRS />
  </THEMROLE>
  <THEMROLE type="Location">
   <SELRESTRS />
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V NP ADJ" secondary="" xtag="" />
   <EXAMPLES>
    <EXAMPLE>
     His property begins at the fence.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS />
    </NP>
    <VERB />
    <PREP value="">
     <SELRESTRS />
    </PREP>
    <NP value="Location">
     <SELRESTRS />
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="has_boundary">
     <ARGS>
      <ARG type="Event" value="E" />
      <ARG type="ThemRole" value="Theme" />
      <ARG type="ThemRole" value="Location" />
     </ARGS>
    </PRED>
    <PRED value="contact">
     <ARGS>
      <ARG type="Event" value="E" />
      <ARG type="ThemRole" value="Theme" />
      <ARG type="ThemRole" value="Location" />
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES />
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/bully-59.5.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="bully-59.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="" name="annoy" verbnet_key="annoy#2" wn="annoy%2:37:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="badger" verbnet_key="badger#1" wn="badger%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="bait" verbnet_key="bait#2" wn="bait%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="bullock" verbnet_key="bullock#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="bully.01" name="bully" verbnet_key="bully#1" wn="bully%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="frighten.01" name="frighten" verbnet_key="frighten#2" wn="frighten%2:37:00" features=""/>
  <MEMBER fn_mapping="None" grouping="goad.01" name="goad" verbnet_key="goad#1" wn="goad%2:37:00 goad%2:35:00 goad%2:35:01 goad%2:32:01" features=""/>
  <MEMBER fn_mapping="None" grouping="harass.01 harass.02" name="harass" verbnet_key="harass#2" wn="harass%2:37:00 harass%2:33:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="harry" verbnet_key="harry#1" wn="harry%2:37:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="hustle" verbnet_key="hustle#1" wn="hustle%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="nag" verbnet_key="nag#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="panic.01" name="panic" verbnet_key="panic#1" wn="panic%2:37:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="shame" verbnet_key="shame#2" wn="shame%2:41:01" features=""/>
  <MEMBER fn_mapping="None" grouping="shock.01" name="shock" verbnet_key="shock#2" wn="shock%2:37:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="taunt" verbnet_key="taunt#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="tease.01" name="tease" verbnet_key="tease#2" wn="tease%2:37:00 tease%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="terrify" verbnet_key="terrify#2" wn="terrify%2:37:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Patient">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Result">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I bullied him.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="hostile"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="negative_emotion"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP S_ING" secondary="NP-P-ING-OC; into-PP" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I bullied him into coming.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
    <PREP value="into">
     <SELRESTRS/>
    </PREP>
    <NP value="Eventuality">
     <SELRESTRS>
      <SELRESTR Value="+" type="oc_ing"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="hostile"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="negative_emotion"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
    <PRED value="act">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="ThemRole" value="Result"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.result" secondary="NP-PP; into-PP" xtag="0.1"/>
   <EXAMPLES>
    <EXAMPLE>
     I bullied John into the chairmanship.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
    <PREP value="into">
     <SELRESTRS/>
    </PREP>
    <NP value="Result">
     <SELRESTRS>
      <SELRESTR Value="-" type="sentential"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="hostile"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="negative_emotion"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
    <PRED value="act">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="ThemRole" value="Result"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/see-30.1.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="see-30.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="tell.02" name="can_tell" verbnet_key="can_tell#1" wn="tell%2:31:00 tell%2:31:01" features=""/>
  <MEMBER fn_mapping="None" grouping="smell.01" name="smell" verbnet_key="smell#1" wn="smell%2:39:01" features=""/>
  <MEMBER fn_mapping="Perception_experience" grouping="taste.01 taste.02" name="taste" verbnet_key="taste#2" wn="taste%2:34:00 taste%2:39:00 taste%2:39:01" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Experiencer">
   <SELRESTRS>
    <SELRESTR Value="+" type="animate"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Stimulus">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.5" primary="NP V that S" secondary="S" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I saw that you were excited.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Experiencer">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Stimulus">
     <SELRESTRS>
      <SELRESTR Value="+" type="that_comp"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="perceive">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Experiencer"/>
      <ARG type="ThemRole" value="Stimulus"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I saw the play.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Experiencer">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Stimulus">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="perceive">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Experiencer"/>
      <ARG type="ThemRole" value="Stimulus"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="2.13.2" primary="NP V NP-ATTR-POS" secondary="Attribute Object Possessor-Attribute Factoring Alternation" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     I sensed the eagerness in him.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Experiencer">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Stimulus">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="perceive">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Experiencer"/>
      <ARG type="ThemRole" value="Stimulus"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V how S" secondary="HOW-S" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I saw how he arrived.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Experiencer">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Stimulus">
     <SELRESTRS>
      <SELRESTR Value="+" type="how_extract"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="perceive">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Experiencer"/>
      <ARG type="ThemRole" value="Stimulus"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V what S" secondary="WHAT-S" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I saw what they did.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Experiencer">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Stimulus">
     <SELRESTRS>
      <SELRESTR Value="+" type="what_extract"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="perceive">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Experiencer"/>
      <ARG type="ThemRole" value="Stimulus"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES>
  <VNSUBCLASS ID="see-30.1-1">
   <MEMBERS>
    <MEMBER fn_mapping="None" grouping="detect.01" name="detect" verbnet_key="detect#1" wn="detect%2:39:00" features=""/>
    <MEMBER fn_mapping="None" grouping="" name="discern" verbnet_key="discern#1" wn="discern%2:39:00" features=""/>
    <MEMBER fn_mapping="Perception_experience" grouping="feel.01 feel.02" name="feel" verbnet_key="feel#4" wn="feel%2:31:00 feel%2:39:00 feel%2:29:00 feel%2:35:00" features=""/>
    <MEMBER fn_mapping="None" grouping="sense.01 sense.03" name="sense" verbnet_key="sense#1" wn="sense%2:39:00" features=""/>
    <MEMBER fn_mapping="Perception_experience" grouping="perceive.01" name="perceive" verbnet_key="perceive#2" wn="" features=""/>
    <MEMBER fn_mapping="Becoming_aware" grouping="notice.01" name="notice" verbnet_key="notice#1" wn="notice%2:39:04 notice%2:39:00" features=""/>
    <MEMBER fn_mapping="Perception_experience" grouping="see.01 see.03" name="see" verbnet_key="see#3" wn="see%2:39:00 see%2:39:02 see%2:36:00 see%2:39:03 see%2:32:00 see%2:41:11 see%2:41:12 see%2:41:10 see%2:39:11 see%2:39:13" features=""/>
   </MEMBERS>
   <THEMROLES/>
   <FRAMES>
    <FRAME>
     <DESCRIPTION descriptionNumber="8.1" primary="NP V S" secondary="NP-INF-OC" xtag="0.2"/>
     <EXAMPLES>
      <EXAMPLE>
       I saw her bake the cake.
      </EXAMPLE>
     </EXAMPLES>
     <SYNTAX>
      <NP value="Experiencer">
       <SELRESTRS/>
      </NP>
      <VERB/>
      <NP value="Stimulus">
       <SELRESTRS>
        <SELRESTR Value="+" type="oc_bare_inf"/>
       </SELRESTRS>
      </NP>
     </SYNTAX>
     <SEMANTICS>
      <PRED value="perceive">
       <ARGS>
        <ARG type="Event" value="e1"/>
        <ARG type="ThemRole" value="Experiencer"/>
        <ARG type="ThemRole" value="Stimulus"/>
       </ARGS>
      </PRED>
     </SEMANTICS>
    </FRAME>
    <FRAME>
     <DESCRIPTION descriptionNumber="8.1" primary="NP V S_ING" secondary="NP-ING-OC" xtag="0.2"/>
     <EXAMPLES>
      <EXAMPLE>
       I saw him laughing.
      </EXAMPLE>
     </EXAMPLES>
     <SYNTAX>
      <NP value="Experiencer">
       <SELRESTRS/>
      </NP>
      <VERB/>
      <NP value="Stimulus">
       <SELRESTRS>
        <SELRESTR Value="+" type="oc_ing"/>
       </SELRESTRS>
      </NP>
     </SYNTAX>
     <SEMANTICS>
      <PRED value="perceive">
       <ARGS>
        <ARG type="Event" value="e1"/>
        <ARG type="ThemRole" value="Experiencer"/>
        <ARG type="ThemRole" value="Stimulus"/>
       </ARGS>
      </PRED>
     </SEMANTICS>
    </FRAME>
    <FRAME>
     <DESCRIPTION descriptionNumber="8.1" primary="NP V S_ING" secondary="POSSING" xtag="0.2"/>
     <EXAMPLES>
      <EXAMPLE>
       I saw their laughing and joking.
      </EXAMPLE>
     </EXAMPLES>
     <SYNTAX>
      <NP value="Experiencer">
       <SELRESTRS/>
      </NP>
      <VERB/>
      <NP value="Stimulus">
       <SELRESTRS>
        <SELRESTR Value="+" type="poss_ing"/>
       </SELRESTRS>
      </NP>
     </SYNTAX>
     <SEMANTICS>
      <PRED value="perceive">
       <ARGS>
        <ARG type="Event" value="e1"/>
        <ARG type="ThemRole" value="Experiencer"/>
        <ARG type="ThemRole" value="Stimulus"/>
       </ARGS>
      </PRED>
     </SEMANTICS>
    </FRAME>
   </FRAMES>
   <SUBCLASSES>
    <VNSUBCLASS ID="see-30.1-1-1">
     <MEMBERS>
      <MEMBER fn_mapping="Perception_experience" grouping="hear.01 hear.02" name="hear" verbnet_key="hear#2" wn="hear%2:39:00 hear%2:31:00 hear%2:39:01 hear%2:39:05" features=""/>
     </MEMBERS>
     <THEMROLES/>
     <FRAMES>
      <FRAME>
       <DESCRIPTION descriptionNumber="" primary="NP V PP.stimulus" secondary="PP; Stimulus-PP" xtag=""/>
       <EXAMPLES>
        <EXAMPLE>
         The entire class heard about/of the sermon.
        </EXAMPLE>
       </EXAMPLES>
       <SYNTAX>
        <NP value="Experiencer">
         <SELRESTRS/>
        </NP>
        <VERB/>
        <PREP value="about of">
         <SELRESTRS/>
        </PREP>
        <NP value="Stimulus">
         <SELRESTRS/>
        </NP>
       </SYNTAX>
       <SEMANTICS>
        <PRED value="perceive">
         <ARGS>
          <ARG type="Event" value="e1"/>
          <ARG type="ThemRole" value="Experiencer"/>
          <ARG type="ThemRole" value="Stimulus"/>
         </ARGS>
        </PRED>
       </SEMANTICS>
      </FRAME>
     </FRAMES>
     <SUBCLASSES/>
    </VNSUBCLASS>
   </SUBCLASSES>
  </VNSUBCLASS>
 </SUBCLASSES>
</VNCLASS>

=== cu-clear/verbnet/verbnet-test/supervision-95.2.2.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="supervision-95.2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER grouping="" name="boss" verbnet_key="boss#2" wn=""/>
  <MEMBER grouping="direct.01" name="direct" verbnet_key="direct#2" wn="direct%2:32:00"/>
  <MEMBER grouping="lead.04" name="lead" verbnet_key="lead#4" wn=""/>
  <MEMBER grouping="manage.02" name="manage" verbnet_key="manage#3" wn="manage%2:41:00 manage%2:41:01"/>
  <MEMBER grouping="" name="superintend" verbnet_key="superintend#1" wn="superintend%2:41:00"/>
  <MEMBER grouping="supervise.01" name="supervise" verbnet_key="supervise#1" wn="supervise%2:41:00 supervise%2:39:00"/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Co-Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V NP.agent" secondary="NP-PP" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     Martha supervises Kevin.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SYNRESTRS/>
    </NP>
    <VERB/>
    <NP value="Co-Agent">
     <SYNRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="authority_relationship">
     <ARGS>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Co-Agent"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>
