=== cu-clear/verbnet/verbnet3.4/vn_class-3.dtd
<!ELEMENT VNCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNCLASS ID ID #REQUIRED
                  xmlns:xsi CDATA #IMPLIED
                  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT VNSUBCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNSUBCLASS ID ID #REQUIRED>

<!ELEMENT MEMBERS (MEMBER*)>
<!ELEMENT THEMROLES (THEMROLE*)>
<!ELEMENT SELRESTRS (SELRESTR|SELRESTRS)*>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT FRAMES (FRAME*)>
<!ELEMENT SUBCLASSES (VNSUBCLASS*)>

<!ELEMENT FRAME (DESCRIPTION,EXAMPLES,SYNTAX,SEMANTICS)>
<!ELEMENT EXAMPLES (EXAMPLE*)>

<!ELEMENT MEMBER EMPTY>
 <!ATTLIST MEMBER name CDATA #REQUIRED
                  wn CDATA #REQUIRED
                  grouping CDATA #IMPLIED
                  fn_mapping CDATA #REQUIRED
                  verbnet_key CDATA #REQUIRED
                  features CDATA #REQUIRED>

<!ELEMENT THEMROLE (SELRESTRS)>
<!ATTLIST THEMROLE type CDATA #REQUIRED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT DESCRIPTION EMPTY>
<!ATTLIST DESCRIPTION primary CDATA #REQUIRED
                      secondary CDATA #IMPLIED
                      descriptionNumber CDATA #REQUIRED 
                      xtag CDATA #REQUIRED> 

<!ELEMENT EXAMPLE (#PCDATA)>
<!ELEMENT SYNTAX (NP|VERB|ADJ|ADV|PREP|LEX)+>
<!ELEMENT SEMANTICS (PRED+)>
<!ELEMENT GL (QUALIA,EVENT_STRUCTURE,SUBCATEGORISATION)>

<!ELEMENT NP (SELRESTRS|SELRESTRS)>
<!ATTLIST NP value CDATA #REQUIRED>

<!ELEMENT SELRESTRS (SELRESTR*)>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT VERB EMPTY>
<!ELEMENT ADJ EMPTY>
<!ELEMENT ADV EMPTY>

<!ELEMENT PREP (SELRESTRS)>
<!ATTLIST PREP value CDATA #IMPLIED>

<!ELEMENT LEX EMPTY>
<!ATTLIST LEX value CDATA #REQUIRED>

<!ELEMENT PRED (ARGS)>
<!ATTLIST PRED bool CDATA #IMPLIED
               value CDATA #REQUIRED>

<!ELEMENT ARGS (ARG+)>
<!ELEMENT ARG EMPTY>
<!ATTLIST ARG type (Event|ThemRole|VerbSpecific|Constant|PredSpecific) #REQUIRED
              value CDATA #REQUIRED>

<!ELEMENT QUALIA (#PCDATA)>
<!ELEMENT EVENT_STRUCTURE (#PCDATA)>
<!ELEMENT SUBCATEGORISATION (#PCDATA)>

=== cu-clear/verbnet/verbnet3.4/trick-59.2.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="trick-59.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="" name="bamboozle" verbnet_key="bamboozle#1" wn="bamboozle%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="cozen.02" name="cozen" verbnet_key="cozen#2" wn="cozen%2:41:01 cozen%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="fox" verbnet_key="fox#2" wn="fox%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="bullshit" verbnet_key="bullshit#1" wn="bullshit%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="bluff" verbnet_key="bluff#1" wn="bluff%2:33:00 bluff%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="blackmail" verbnet_key="blackmail#1" wn="blackmail%2:41:00 blackmail%2:40:00" features=""/>
  <MEMBER fn_mapping="None" grouping="cheat.02" name="cheat" verbnet_key="cheat#2" wn="cheat%2:33:00" features=""/>
  <MEMBER fn_mapping="None" grouping="con.01" name="con" verbnet_key="con#2" wn="con%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="deceive.01" name="deceive" verbnet_key="deceive#1" wn="deceive%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="delude" verbnet_key="delude#1" wn="delude%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="dupe" verbnet_key="dupe#1" wn="dupe%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="ensnare" verbnet_key="ensnare#1" wn="ensnare%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="entrap" verbnet_key="entrap#1" wn="entrap%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="extort" verbnet_key="extort#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="fool.01" name="fool" verbnet_key="fool#1" wn="fool%2:32:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="hoodwink" verbnet_key="hoodwink#1" wn="hoodwink%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="manipulate.01" name="manipulate" verbnet_key="manipulate#1" wn="manipulate%2:41:00 manipulate%2:37:00" features=""/>
  <MEMBER fn_mapping="None" grouping="mislead.01 mislead.02" name="mislead" verbnet_key="mislead#1" wn="mislead%2:32:00" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="trick" verbnet_key="trick#2" wn="trick%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="trap.01" name="trap" verbnet_key="trap#2" wn="trap%2:41:00" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Patient">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Result">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I tricked him.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="deceptive"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="deceived"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP S_ING" secondary="NP-P-ING-OC; into-PP" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     I tricked him into coming.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
    <PREP value="into">
     <SELRESTRS/>
    </PREP>
    <NP value="Result">
     <SELRESTRS>
      <SELRESTR Value="+" type="oc_ing"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="deceptive"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="deceived"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
    <PRED value="act">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="ThemRole" value="Result"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.result" secondary="NP-PP; into-PP" xtag="0.1"/>
   <EXAMPLES>
    <EXAMPLE>
     I tricked John into the chairmanship.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Patient">
     <SELRESTRS/>
    </NP>
    <PREP value="into">
     <SELRESTRS/>
    </PREP>
    <NP value="Result">
     <SELRESTRS>
      <SELRESTR Value="-" type="sentential"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="do">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="manner">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Constant" value="deceptive"/>
      <ARG type="ThemRole" value="Agent"/>
     </ARGS>
    </PRED>
    <PRED value="has_emotional_state">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="Constant" value="deceived"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e2"/>
     </ARGS>
    </PRED>
    <PRED value="act">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Patient"/>
      <ARG type="ThemRole" value="Result"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet-test/illustrate-25.3.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="illustrate-25.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="address.06" name="address" verbnet_key="address#1" wn="address%2:32:03"/>
  <MEMBER fn_mapping="Filling" grouping="adorn.01" name="adorn" verbnet_key="adorn#2" wn="adorn%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="" name="autograph" verbnet_key="autograph#1" wn="autograph%2:32:00"/>
  <MEMBER fn_mapping="None" grouping="bead.02" name="bead" verbnet_key="bead#2" wn="bead%2:36:00 bead%2:35:00"/>
  <MEMBER fn_mapping="None" grouping="brand.01" name="brand" verbnet_key="brand#2" wn="brand%2:41:01"/>
  <MEMBER fn_mapping="None" grouping="date.02" name="date" verbnet_key="date#1" wn="date%2:31:02 date%2:31:01"/>
  <MEMBER fn_mapping="Distributed_position" grouping="decorate.01" name="decorate" verbnet_key="decorate#2" wn="decorate%2:35:00"/>
  <MEMBER fn_mapping="Filling" grouping="embellish.01 embellish.02" name="embellish" verbnet_key="embellish#2" wn="embellish%2:32:00 embellish%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="endorse.03" name="endorse" verbnet_key="endorse#2" wn="endorse%2:32:00"/>
  <MEMBER fn_mapping="None" grouping="" name="gild" verbnet_key="gild#2" wn=""/>
  <MEMBER fn_mapping="None" grouping="ice.01" name="ice" verbnet_key="ice#2" wn="ice%2:35:00"/>
  <MEMBER fn_mapping="None" grouping="illuminate.03" name="illuminate" verbnet_key="illuminate#1" wn="illuminate%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="illustrate.01" name="illustrate" verbnet_key="illustrate#1" wn="illustrate%2:36:01"/>
  <MEMBER fn_mapping="None" grouping="" name="initial" verbnet_key="initial#1" wn="initial%2:32:00"/>
  <MEMBER fn_mapping="None" grouping="label.02" name="label" verbnet_key="label#3" wn="label%2:35:00"/>
  <MEMBER fn_mapping="None" grouping="letter.02" name="letter" verbnet_key="letter#1" wn="letter%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="" name="monogram" verbnet_key="monogram#1" wn=""/>
  <MEMBER fn_mapping="None" grouping="" name="ornament" verbnet_key="ornament#3" wn="ornament%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="" name="redecorate" verbnet_key="redecorate#2" wn="redecorate%2:36:00"/>
  <MEMBER fn_mapping="None" grouping="tag.01 tag.04" name="tag" verbnet_key="tag#2" wn="tag%2:35:00"/>
 </MEMBERS>
 <THEMROLES>
  <!--In most predicates, such as location, Theme really means image_of(Theme)-->
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="machine"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Destination">
   <SELRESTRS>
    <SELRESTR Value="+" type="concrete"/>
   </SELRESTRS>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     The jeweler decorated the ring.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SYNRESTRS/>
    </NP>
    <VERB/>
    <NP value="Destination">
     <SYNRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED bool="!" value="be">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="?Theme"/>
     </ARGS>
    </PRED>
    <PRED value="create_image">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="?Theme"/>
     </ARGS>
    </PRED>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="?Theme"/>
     </ARGS>
    </PRED>
    <PRED value="part_of">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="?Theme"/>
      <ARG type="ThemRole" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP PP.theme" secondary="NP-PP; with-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     The jeweler decorated the ring with the name.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SYNRESTRS/>
    </NP>
    <VERB/>
    <NP value="Destination">
     <SYNRESTRS/>
    </NP>
    <PREP value="with">
     <SELRESTRS/>
    </PREP>
    <NP value="Theme">
     <SYNRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED bool="!" value="be">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="create_image">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="be">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
     </ARGS>
    </PRED>
    <PRED value="part_of">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="cause">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="Event" value="e3"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/harmonize-22.6.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="harmonize-22.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="" name="alternate" verbnet_key="alternate#3" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="cohere" verbnet_key="cohere#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="couple" verbnet_key="couple#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="dovetail" verbnet_key="dovetail#1" wn="" features=""/>
  <MEMBER fn_mapping="Compatibility" grouping="go.14" name="go" verbnet_key="go#6" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="pair" verbnet_key="pair#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="harmonize" verbnet_key="harmonize#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="jibe" verbnet_key="jibe#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="match" verbnet_key="match#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="rhyme" verbnet_key="rhyme#2" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="square" verbnet_key="square#1" wn="" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Co-Theme">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V ADV" secondary="" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Peaches and cream pair well (together).
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS>
      <SELRESTR Value="+" type="plural"/>
     </SELRESTRS>
    </NP>
    <VERB/>
    <ADV/>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="harmonize">
     <ARGS>
      <ARG type="Event" value="E"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Co-Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V PP" secondary="" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Peaches pair with cream.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Co-Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="harmonize">
     <ARGS>
      <ARG type="Event" value="E"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Co-Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V ADV PP" secondary="" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Peaches pair well with cream.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <ADV/>
    <NP value="Co-Theme">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="harmonize">
     <ARGS>
      <ARG type="Event" value="E"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Co-Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.1" primary="NP V" secondary="Intransitive; Plural Subject" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Blue and grey match.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS>
      <SELRESTR Value="+" type="plural"/>
     </SELRESTRS>
    </NP>
    <VERB/>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="harmonize">
     <ARGS>
      <ARG type="Event" value="E"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Co-Theme"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/orbit-51.9.2.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="orbit-51.9.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="None" grouping="" name="orbit" verbnet_key="orbit#1" wn="orbit%2:38:00" features=""/>
  <MEMBER fn_mapping="None" grouping="revolve.01" name="revolve" verbnet_key="revolve#2" wn="revolve%2:38:01" features=""/>
  <MEMBER fn_mapping="None" grouping="rotate.01" name="rotate" verbnet_key="rotate#3" wn="rotate%2:38:01" features=""/>
  <MEMBER fn_mapping="None" grouping="" name="twirl" verbnet_key="twirl#3" wn="twirl%2:38:01" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Theme">
   <SELRESTRS/>
  </THEMROLE>
  <THEMROLE type="Axis">
   <!-- Subcategory of LOCATION/PATH, indicating a path around the axis. -->
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V PP.location" secondary="NP-PP; path-PP" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     The Earth revolved around the Sun.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Theme">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <PREP>
     <SELRESTRS>
      <SELRESTR Value="+" type="path"/>
     </SELRESTRS>
    </PREP>
    <NP value="Axis">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e1"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Initial_Location"/>
     </ARGS>
    </PRED>
    <PRED value="elliptical_motion">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="ThemRole" value="Axis"/>
     </ARGS>
    </PRED>
    <PRED bool="!" value="has_location">
     <ARGS>
      <ARG type="Event" value="ë2"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Initial_Location"/>
     </ARGS>
    </PRED>
    <PRED value="has_location">
     <ARGS>
      <ARG type="Event" value="e3"/>
      <ARG type="ThemRole" value="Theme"/>
      <ARG type="PredSpecific" value="Destination"/>
     </ARGS>
    </PRED>
    <PRED value="equals">
     <ARGS>
      <ARG type="PredSpecific" value="Initial_Location"/>
      <ARG type="PredSpecific" value="Destination"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>

=== cu-clear/verbnet/verbnet3.4/complete-55.2.xml
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="complete-55.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
 <MEMBERS>
  <MEMBER fn_mapping="Accomplishment" grouping="accomplish.01" name="accomplish" verbnet_key="accomplish#1" wn="accomplish%2:36:00 accomplish%2:41:00" features=""/>
  <MEMBER fn_mapping="Accomplishment" grouping="achieve.01" name="achieve" verbnet_key="achieve#1" wn="achieve%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="bring.08" name="bring-off" verbnet_key="bring-off#1" wn="" features=""/>
  <MEMBER fn_mapping="None" grouping="complete.01 complete.02 complete.03" name="complete" verbnet_key="complete#1" wn="complete%2:30:02 complete%2:30:00 complete%2:41:00" features=""/>
  <MEMBER fn_mapping="None" grouping="pull.04" name="pull-off" verbnet_key="pull-off#1" wn="" features=""/>
 </MEMBERS>
 <THEMROLES>
  <THEMROLE type="Agent">
   <SELRESTRS logic="or">
    <SELRESTR Value="+" type="animate"/>
    <SELRESTR Value="+" type="organization"/>
   </SELRESTRS>
  </THEMROLE>
  <THEMROLE type="Eventuality">
   <SELRESTRS/>
  </THEMROLE>
 </THEMROLES>
 <FRAMES>
  <FRAME>
   <DESCRIPTION descriptionNumber="0.2" primary="NP V NP" secondary="Basic Transitive" xtag=""/>
   <EXAMPLES>
    <EXAMPLE>
     Wilma completed the assignment.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Eventuality">
     <SELRESTRS/>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="engage_in">
     <ARGS>
      <ARG type="Event" value="ë1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Eventuality"/>
     </ARGS>
    </PRED>
    <PRED value="completed">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Eventuality"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
  <FRAME>
   <DESCRIPTION descriptionNumber="8.1" primary="NP V S_ING" secondary="ING-SC/BE-ING-SC" xtag="0.2"/>
   <EXAMPLES>
    <EXAMPLE>
     She completed running the race.
    </EXAMPLE>
   </EXAMPLES>
   <SYNTAX>
    <NP value="Agent">
     <SELRESTRS/>
    </NP>
    <VERB/>
    <NP value="Eventuality">
     <SELRESTRS>
      <SELRESTR Value="+" type="be_sc_ing"/>
     </SELRESTRS>
    </NP>
   </SYNTAX>
   <SEMANTICS>
    <PRED value="engage_in">
     <ARGS>
      <ARG type="Event" value="ë1"/>
      <ARG type="ThemRole" value="Agent"/>
      <ARG type="ThemRole" value="Eventuality"/>
     </ARGS>
    </PRED>
    <PRED value="completed">
     <ARGS>
      <ARG type="Event" value="e2"/>
      <ARG type="ThemRole" value="Eventuality"/>
     </ARGS>
    </PRED>
   </SEMANTICS>
  </FRAME>
 </FRAMES>
 <SUBCLASSES/>
</VNCLASS>
